=== tgaillard1/ub-services/service-1/src/main/resources/samples/inventory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://everythingjboss.org/inventory"
	xmlns:tns="http://everythingjboss.org/inventory" elementFormDefault="qualified">

	<element name="inventory">
		<complexType>
			<sequence>
				<element name="product" type="tns:product" maxOccurs="unbounded"
					minOccurs="1" />
			</sequence>
		</complexType>
	</element>

	<complexType name="product">
		<sequence>
			<element name="name" type="string" />
			<element name="type" type="tns:type" />
			<element name="price" type="string" />
		</sequence>
	</complexType>

	<simpleType name="type">
		<restriction base="string">
			<enumeration value="type-2" />
			<enumeration value="type-3" />
		</restriction>
	</simpleType>
</schema>

=== tgaillard1/ub-services/service-3/src/main/resources/samples/inventory.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:inventory xmlns:tns="http://everythingjboss.org/inventory"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://everythingjboss.org/inventory inventory.xsd ">
	<tns:product>
		<tns:name>A</tns:name>
		<tns:type>type-2</tns:type>
		<tns:price></tns:price>
	</tns:product>
	<tns:product>
		<tns:name>B</tns:name>
		<tns:type>type-3</tns:type>
		<tns:price></tns:price>
	</tns:product>
</tns:inventory>
